from fastapi_mail import FastMail, MessageSchema, ConnectionConfig
from pydantic import EmailStr
from config import settings

# Configuration for FastAPI-Mail
conf = ConnectionConfig(
    MAIL_USERNAME=settings.MAIL_USERNAME,
    MAIL_PASSWORD=settings.MAIL_PASSWORD,
    MAIL_FROM=settings.MAIL_FROM,
    MAIL_PORT=settings.MAIL_PORT,
    MAIL_SERVER=settings.MAIL_SERVER,
    MAIL_FROM_NAME=settings.MAIL_FROM_NAME,
    MAIL_STARTTLS=settings.MAIL_STARTTLS,
    MAIL_SSL_TLS=settings.MAIL_SSL_TLS,
    USE_CREDENTIALS=True,
    VALIDATE_CERTS=True # Set to False only for testing with self-signed certs
)


# Create a single FastMail instance
fm = FastMail(conf)

async def send_verification_email(email: EmailStr, token: str):
    """
    Send a verification email with a link containing the token.
    :param email: The recipient's email address.
    :param token: The verification token generated by FastAPI-Users.
    """
    # Construct the verification link. Adjust the URL to your frontend.
    verification_link = f"{settings.FRONTEND_URL}/verify-email?token={token}"
    
    html_body = f"""
    <p>Thanks for registering!</p>
    <p>Please click the link below to verify your email address:</p>
    <p><a href="{verification_link}">Verify your email</a></p>
    <p>If you didn't create an account, you can safely ignore this email.</p>
    """
    
    message = MessageSchema(
        subject="Verify your email address",
        recipients=[email], # List of recipients
        body=html_body,
        subtype="html"
    )
    
    await fm.send_message(message)
    print(f"Verification email sent to {email}")


async def send_reset_password_email(email: EmailStr, token: str):
    reset_link = f"{settings.FRONTEND_URL}/reset-password?token={token}"
    html_body = f"""
    <p>You requested to reset your password.</p>
    <p>Click the link below to set a new password:</p>
    <p><a href="{reset_link}">Reset your password</a></p>
    <p>If you didn't request this, you can safely ignore this email.</p>
    """
    message = MessageSchema(
        subject="Reset your password",
        recipients=[email],
        body=html_body,
        subtype="html"
    )
    await fm.send_message(message)